# Generated by Django 2.1.7 on 2019-03-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
    ]
